### ISSUE TITLE
非常赞，要是能自动导入当期卡池配置就好了

### ISSUE THREAD

**Issue by NepPure** [Hellobaka/BH3rdGachaSimulator#1]
比如直接从公告信息粘贴识别

```
【★4武器】

双枪：幽色咏叹调

太刀：仿灵刀·冰昙天

重炮：火刀·真田

十字架：埃琉德尼尔

太刀：灵刀·樱吹雪

拳套：断光之努亚达

镰刀：阿芙洛狄忒

【★4圣痕】

崩坏女王套装：西琳·升华（上、中、下）

布拉格寒鸦套装：卡夫卡（上、中、下）

远古意志套装：绯玉丸（上、中、下）

冰影之蝶套装：浓姬（上、中、下）

唯美艺术家套装：王尔德（上、中、下）
```

然后从里面选择一下UP之类的

https://www.bh3.com/news/6476?cate=171

**Comment by Hellobaka** [comment]
哇，第一个issue！
确实，手动更换池子比较麻烦，我最近也觉得烦了，这个功能mark了。
这个功能要实现的应该就是每天爬取新公告了，咱没这方面的知识，或许实现起来有点难度，这个应该就是咱的第一个爬虫程序了hhh

**Comment by NepPure** [comment]
爬取可能比较麻烦，你还得猜这是不是池子更新的公告2333，不过加油~o(￣▽￣)ｄ

**Comment by NepPure** [comment]
还有个办法是在github上维护一个文本文件，工具里配置url链接，这样一个人维护所有人受益

**Comment by Hellobaka** [comment]
确实想到这个方法了，目前检测更新的功能就是基于仓库内的New.json实现的。
不过还是想试试爬虫是啥样的，还没接触过这项技术hhh，毕竟机器干活谁不i呢

**Comment by NepPure** [comment]
![image](https://user-images.githubusercontent.com/12379907/78452331-4bc01f00-76bd-11ea-86e8-63ebd4e2be2c.png)

可能需要OCR或者图片识别之类的，比如这个公告的文字里完全没有迅羽

https://www.bh3.com/news/6435?cate=171

**Comment by Hellobaka** [comment]
![Q8@ ISLQBPCGR5 N_MVA@0H](https://user-images.githubusercontent.com/50934714/79296291-989dc400-7f0d-11ea-929f-e8367c798e26.png)
马上了哦(￣ε(#￣)

**Comment by NepPure** [comment]
大老牛逼！——（破音

**Comment by Hellobaka** [comment]
实装了这个功能，不过只能整精准和扩充，其他类型的补给都不行，扩充甚至只能获取第一轮次的
(╯‵□′)╯︵┻━┻
后续再实装通过获取到的时间来定时更换，感谢建议，非常实用

**Comment by NepPure** [comment]
大佬牛逼！用AI服务去识别确实不错，省事！

**Comment by NepPure** [comment]
今天终于有空试了一下

![image](https://user-images.githubusercontent.com/12379907/82108765-6f1dc580-9763-11ea-9944-bf8b7830249c.png)

识别还是有点问题 A级角色好像并没有给出结果

**Comment by NepPure** [comment]
![image](https://user-images.githubusercontent.com/12379907/82108795-d63b7a00-9763-11ea-9af8-c3478508598e.png)

这次精准的好用

**Comment by NepPure** [comment]
![image](https://user-images.githubusercontent.com/12379907/82108873-72fe1780-9764-11ea-9467-a699285f05ce.png)

更换完成后精准B的其他圣痕还是上次配置的

**Comment by Hellobaka** [comment]
OCR上出了点问题，扩充暂时用不了，不过精准是没问题的。公告上确实说B池是提尔和牛，上期B池是神陨剑和泰勒斯

**Comment by NepPure** [comment]
B池的额外圣痕没更新，只更新了UP

```
黑暗之喻套装：爱伦·坡（上、中、下）

力学三定律套装: 伊萨克·牛顿（上、中、下）

诅咒之影套装: 古斯塔夫·克里姆特（上、中、下）

逆熵乐队套装: 特斯拉·乐队（上、中、下）

北极探险家套装: 罗伯特·皮里（上、中、下）
```
![image](https://user-images.githubusercontent.com/12379907/82108963-50b8c980-9765-11ea-8093-1f2c73abaf40.png)

**Comment by Hellobaka** [comment]
哦！A池的圣痕换了，B池的圣痕没换，发现问题了，我尽快修

**Comment by Hellobaka** [comment]
已修复，可在Release下载|ू･ω･` )

**Comment by NepPure** [comment]
非常好用
