### ISSUE TITLE
抽干家底功能建议计算一次祈愿

### ISSUE THREAD

**Issue by NepPure** [Hellobaka/BH3rdGachaSimulator#3]
不然。，。。

![image](https://user-images.githubusercontent.com/12379907/82401691-131dae80-9a8d-11ea-8e8c-7617f99a084d.png)

**Comment by Hellobaka** [comment]
抱歉……issue提醒不知道怎么关了，现在才看issue，（其实183次也不算高，我群有300+的……）祈愿屋是个好东西，建议收下了，等最近安定下来了就来实现

**Comment by NepPure** [comment]
大佬你来啦 酷Q已经跑路了

**Comment by Hellobaka** [comment]
我知道啊，所以在readme加了个搬家到mirai的教程，在release加了这个插件的dll和json，说实话啊，离了酷Q真的不适应，开发各种不适应……哎，希望再来一个稳定的框架吧
